// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bdfkxzkiwzmwkdghvmoi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkZmt4emtpd3ptd2tkZ2h2bW9pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNzU5MDUsImV4cCI6MjA3MDc1MTkwNX0.Q4L7q_6aB_Ul9JApFaUFTq9ktC_qMknS6XD1Xg4q0MM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});